[workspace]
members = [
  "bin",
  "libprocess-sys",
]

resolver = "2"

[profile.release]
opt-level = 3
debug = true
lto = true

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
libc = "0.2"
